### ISSUE TITLE
Can't show image in real iphone

### ISSUE THREAD

**Issue by freyue** [myang-git/QR-Code-Encoder-for-Objective-C#1]
Hi Myang, I downloaded your code and use it as you mentioned in readme file, it could work well in simulator, but in iphone there only show one black image, I have no idea why this problem exist, have you ever run this code in real device ?
any reply is appreciate, thanks a lot!

**Comment by myang-git** [comment]
Hi, it works fine on my iPod Touch running iOS 4.3.5. Can you provide more detail about your test enviroment?

**Comment by freyue** [comment]
I am using iPod Touch running 4.3.3 and iphone with ios 4.2, both can't work, how can I upload my test project to this website?
a view-based application and import all the encoder source code into it, very simple.
this is the source code of response function to a button:
- (IBAction)GenerateQRCode:(id)sender
  {
  NSString *text = textView.text;
  
  int qrcodeImageDimension = 250;
  
  DataMatrix\* qrMatrix = [QREncoder encodeWithECLevel:QR_ECLEVEL_AUTO version:QR_VERSION_AUTO string:text];
  
  //then render the matrix
  UIImage\* qrcodeImage = [QREncoder renderDataMatrix:qrMatrix imageDimension:qrcodeImageDimension];
  
  [imageView setImage:qrcodeImage];
  [imageView sizeToFit];

}

or could you tell me how you implement this exactly, thanks!

**Comment by myang-git** [comment]
Hello, I can only (kind of) reproduce the problem by encoding a very large piece of text. You may need to check the size of the text. Also try removing the call [imageView sizeToFit]. You can send me the entire project so I can take a look. Thanks.

**Comment by freyue** [comment]
I use CGBitmapContextCreateImage to create the CGImageRef in renderDataMatrix, and everything works fine now, thanks a lot!
in my device it always be a black image with the original code, no matter with the text size, have no idea :(

**Comment by myang-git** [comment]
That's interesting.. I will make a change to the encode to use the mentioned method if it's more compatible. Good to know it's now working on your device. Thanks.
