### ISSUE TITLE
QRCode generation without the white border

### ISSUE THREAD

**Issue by carlj** [myang-git/QR-Code-Encoder-for-Objective-C#10]
Hi,

how can i generate a QRCode UIImage without the white border around the QRCode?

Best Regards

**Comment by carlj** [comment]
ok i solved it:

```
  NSString *test = @"My Test String";
  DataMatrix* qrMatrix = [QREncoder encodeWithECLevel: QR_ECLEVEL_L version: QR_VERSION_AUTO string: test];

  int qrcodeImageDimension = [qrMatrix dimension];
  UIImage* qrcodeImage = [QREncoder renderDataMatrix: qrMatrix imageDimension: qrcodeImageDimension];

  UIImageView* qrcodeImageView = [[UIImageView alloc] initWithImage:qrcodeImage];
  qrcodeImageView.layer.magnificationFilter = kCAFilterNearest;

  CGFloat imageSize = 300.0f
  [qrcodeImageView setFrame:CGRectMake(0, 0, imageSize, imageSize)];

  [self.view addSubview:qrcodeImageView];
  [qrcodeImageView release];

```

Don't forget to import `#import <QuartzCore/QuartzCore.h>`

**Comment by myang-git** [comment]
The white border can be avoided by controlling the offset value in renderDataMatrix:imageDimension: in QREncoder class. Since the QR code may not perfectly fit the specified image dimension, you can calculate the required image size reversely if knowing the dimension of the QR code matrix.

**Comment by jlewisiii** [comment]
Hi Carl,

Did this work consistently without a white border?  I am working to put a QR code on a black background and don't want to have the white box. It is to be used within an overall design and I don't want the full distraction from the art. Before I attempt this, wanted to get your take. 

Thanks! Jim

**Comment by myang-git** [comment]
Hi Jim, you can back out the size of the QR code area (not the entire image) and extract it from the image.
