### ISSUE TITLE
how use in ios5 with storyboard

### ISSUE THREAD

**Issue by edwinps** [myang-git/QR-Code-Encoder-for-Objective-C#15]
I tried to implement the qrencode in my project but I'm using storyboard and I have errors in this line
class CQR_Encode
the errors 
unknown type name 'class'; did you mean 'Class'?
expected ';' after top level declarator

I already change the. m a. mm but equal does not work,I do not know if anyone has implemented in IOS5
i help a littler help

**Comment by myang-git** [comment]
you may have other .m files that are indirectly referencing to the QR encoder. those files need to have .mm extension as well.

**Comment by edwinps** [comment]
no , all my .m i changed to .mm

AppDelegate.mm
ViewController.mm

and the folder QRCodeEncoderObjectiveCAtGithub 
i didn't change anything

**Comment by myang-git** [comment]
you can send me your project to take a look if you don't mind.

**Comment by edwinps** [comment]
thank you

**Comment by gwbennett** [comment]
I am having the same issue with getting class CQR_Encode
the errors 
unknown type name 'class'; did you mean 'Class'?

How did you resolve it?

**Comment by myang-git** [comment]
renaming the .m files to .mm
Also are you able to build the demo app?

**Comment by visum** [comment]
Moving the 
#import "QREncoder.h"
directive from the .h to the .mm file of the referencing class resolved the issue for me.
