### ISSUE TITLE
running the application

### ISSUE THREAD

**Issue by rutvijk** [myang-git/QR-Code-Encoder-for-Objective-C#19]
Hi myang,

Thank you for sharing the code. Can you please share an instruction file about how to run the code? I tried opening ReadMe, but it does not open. 

Thanks!

Cheers!

**Comment by myang-git** [comment]
The instructions are right on the github page, or alternatively you can take a look at the README.md file directly: https://github.com/myang-git/QR-Code-Encoder-for-Objective-C/blob/master/README.md
