### ISSUE TITLE
expected '=', ',', ';', 'asm' or '__attribute__' before 'class'

### ISSUE THREAD

**Issue by pec1985** [myang-git/QR-Code-Encoder-for-Objective-C#2]
Getting the error in the title in line 89 of QR_Encode.h

```
class CQR_Encode
{
```

**Comment by myang-git** [comment]
you need to rename the implementation files that directly or indirectly reference the QR encoder to *.mm

**Comment by pec1985** [comment]
whoa, that was quick, let give it a try, and thanks!

:)

**Comment by pec1985** [comment]
Awesome!!!!

Thanks again.

Closing issue
