### ISSUE TITLE
Issues with Xcode 4.2 ??

### ISSUE THREAD

**Issue by alexherbs** [myang-git/QR-Code-Encoder-for-Objective-C#3]
Hello,

I'm using xcode 4.2 (4C199) and I followed every step about 5 or 6 times but it just doesn't work
I also tried to fix it on my own but I ALWAYS get these two issues: 

QR_Encode.h:81:1: error: unknown type name 'class'; did you mean 'Class'? [3]
QR_Encode.h:81:17: error: expected ';' after top level declarator [1]

Hope you can help me.

Thx. Alex

**Comment by myang-git** [comment]
Does your implementation file have extension of ".m" or ".mm" ?

**Comment by alexherbs** [comment]
Hello myang. Thanks for your fast reply. I've changed the implementation file to *.mm and it works now :) It is also very important to import the "QREncoder.h" file just in the *.mm file ! That was my generall mistake.
