### ISSUE TITLE
Getting errors in 

### ISSUE THREAD

**Issue by tblack2200** [myang-git/QR-Code-Encoder-for-Objective-C#4]
I'm getting multiple errors in the QR_Encode.h file on line # 81 when I try to build a demo app.  I've followed the instructions for dragging the project over, setting the dependency and adding the linked library.

The line contains:
class CQR_Encode

The errors are:
-Unknown type name 'class'; did you mean 'Class'?
-Expected ';' after top level declarator

Thanks

**Comment by myang-git** [comment]
Does you implementation file have extension as ".m" or ".mm"? You should make it ".mm"

**Comment by tblack2200** [comment]
Thank you so much for the quick reply!

I did change it to .mm, but the errors persist.  I basically created a single view IOS app (target is 4.3), which has the .h, .m and .xib files.  I renamed the .m file to a .mm file.

**Comment by myang-git** [comment]
You need to change the extension to ".mm" for all implementation files that directly or indirectly reference the QREncoder. If you don't mind you can send me your test project and I will check it out.

**Comment by tblack2200** [comment]
Here you go...

**Comment by myang-git** [comment]
Where did you send it to?

**Comment by tblack2200** [comment]
I just replied to your email with a zip attachment of the project.

**Comment by myang-git** [comment]
Not sure if you can reply with an attachment. Just sent it to myang-git -at- gmail.com

**Comment by tblack2200** [comment]
OK, I sent it to the other email.

**Comment by tblack2200** [comment]
It didn't like the email address of: myang-git@gmail.com

**Comment by myang-git** [comment]
sorry had a typo. it's myang.git -at- gmail.com

**Comment by myang-git** [comment]
Looked into your source code. You need to rename ViewController.m to ViewController.mm
After renaming it the project built without problem in my xcode.

**Comment by tblack2200** [comment]
Thank you so much Ming!

I also had to use a .mm extension for the AppDelegate.  So, every implementation file in my project from this point forward will require the .mm naming convention?

Thanks again...I've been searching for a way to generate QR codes on the iPhone.  Great Job!!

**Comment by myang-git** [comment]
Sounds great! You don't need to rename every implementation file to *.mm. Only do that for the ones that directly or indirectly reference the QREncoder. If AppDelegate.h or AppDelegate.m references it, then AppDelegate.m has to be renamed to *.mm
Hope this helps.
