### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by rpledge** [myang-git/QR-Code-Encoder-for-Objective-C#7]
Great project, it was super easy for me to get working.  Maybe I'm blind but I don't see any licence info in the project.  Do you have any restriction on what I do with this?

**Comment by myang-git** [comment]
Hi, part of this library is ported from Psytec's work. According to their website at http://www.psytec.co.jp/condition
the encoder source code is free for commercial and non-commercial use, without attribution to the company. 
For the Objective-C wrapper and other additions, it's released under Apache License Version 2.0. I have added a license file to the repository. Thanks!

**Comment by rpledge** [comment]
Thank you very much.  Your codes worked flawlessly for me so far.

**Comment by myang-git** [comment]
great! glad to hear that
