### ISSUE TITLE
armv6 architecture issue

### ISSUE THREAD

**Issue by nvilmart** [myang-git/QR-Code-Encoder-for-Objective-C#8]
Hi,

Thank you for this code and for related doc! Very helpful!

I face an issue trying to instal my app, build with QR Code Encoder, on iPhone 3G (armv6).
It looks impossible to build the QRCodeEncoderObjectiveC project with armv6 architecture.

If you have some help, I would be grateful!

Thank you,
Nicolas

**Comment by myang-git** [comment]
Are you able to build the static library alone?

**Comment by nvilmart** [comment]
Yes, it builds correctly with armv7 and armv6 architectures.
When I try to build the app i get these errors:
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_QREncoder", referenced from:
      objc-class-ref in MyFile1.o
      objc-class-ref in MyFile2.o
      objc-class-ref in MyFile3.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nvilmart** [comment]
Problem solved! I was trying to build with a wrong build setup:
- Static lib build settings: armv6; $(ARCHS_STANDARD_32_BIT)
- App build settings: armv6; armv7
- App and Lib minimum iOS version target: 4.0
  Sorry for this "non-issue", I'm still quite young in iOS dev scene...
  KR,
  Nicolas

**Comment by myang-git** [comment]
Great. Just out of curiosity what change did you made to fix the problem?

**Comment by nvilmart** [comment]
I just switched target architecture of static library from Std armv7 to armv6; $(ARCHS_STANDARD_32_BIT).
And I changed iOS deployment target from 4.3 to 4.0.
Then I changed my App architecture to armv6; armv7.
I also changed extension of files listed in error from .h to .cpp!
Then it builds correctly!
Thank you again for this lib, it works perfectly.
