### ISSUE TITLE
Semantic Issue

### ISSUE THREAD

**Issue by ghost** [myang-git/QR-Code-Encoder-for-Objective-C#9]
I have renamed my implmentation file that makes use of QREncoder.h, yet I still "unknown type class" which flags QR_Encode.h.  I even went all the way up to main.m and renamed it main.mm.

I realize this has been asked many times before, but I have followed those instructions, yet I still the error.  Any ideas?

**Comment by myang-git** [comment]
You need to rename all files that reference to QREncoder.h, either directly or indirectly. If you don't mind I can take a look at your code to find out why.
